# Site settings
title: Bad Circuits - blog about microcontrollers (AVR, Arduino)
email: eug.nikolaev@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Blog about microcontrollers, electronics and schematics. Digital and not only.
highlighter: rouge
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://badcircuits.com" # the base hostname & protocol for your site