# Site settings
title: Bad Circuits - amauter electronics blog)
email: eug.nikolaev@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Blog about electronics and schematics. Digital, microcontrollers and not only.
highlighter: rouge
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://badcircuits.com" # the base hostname & protocol for your site
permalink: /:title.html